# Jekyll Digital Collection Generator

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build

# Site/Collection settings
title: Dworshak Dam Collection
tagline: Documenting the Development and Construction of the Doworshak Dam, 1952 - 1975
subjects: Dams; Construction; Water; Northwest; Idaho; Maps; #separate semi-colon(';')
description: "Digitized photographs and documents pertaining to the planning, development and construction of the Dworshak Dam, featuring documents and photographs detailing both the legislative and physical development of the dam." 
mediatypes: documents; correspondence; images #options[documents,images,video,sound,data] separate semi-colon(';')
locations: Dworshak Dam, Idaho #separate by semi-colon(';')
latitude: 46.515697 #to determine center of map
longitude: -116.296881 #to determine center of map

# repository variables (leave blank if self-contained)
repo-url: https://digital.lib.uidaho.edu 
repo-collection-id: dworshak
repo-link: on #options[on] - if on, will link to base repository item url outside of directory; if blank, will link to item url within directory, which will require the page-gen settings to be turned on below-- NOTE: these item pages will not work via Github Pages

# Site Population settings
csvtitle: dworshak
pagetypes: data,map,timeline,about #options for pagetypes- [data,map,timeline,about] -- home, browse, and subjects are auotmatic
subjectsplit: subjects # options[subjects - whole subjects, including two word entries separted by semi-colon; words - breaks all subjects into individual words]
mapzoomlevel: 10 # options - 
homepagetype: infographic # options for homepage type [basic,infographic]
datatable: title,creator,description,date,subjects,source # options any field on csv [title,creator,date,description,location,subjects,latitude,longitude,format,type,object-id]


# url variables
url: https://dcnb.github.io
baseurl: /jekyll-collection-contentdm
email: dbecker@uidaho.edu
# Item Page Details

# collection  display variables 
# see _data/metadata-fields.csv

# page gen settings https://github.com/avillafiorita/jekyll-datapage_gen
page_gen:
  - data: 'dworshak' #should be the same as your csvtitle above
    template: 'items' 
    name: 'object-id' #name of the unique identifier in your metadata sheet
    dir: 'items' #which directory you'd like your pages generated to
    extension: 'html'