# Jekyll Digital Collection Generator

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build

# Site settings
title: Potlatch Historical Society Collection
tagline: Potlatch Historical Society Collection Depicting life in and around Potlatch, Idaho from 1880 to 1998
description: "Potlatch Historical Society Collection Depicting life in and around Potlatch, Idaho from 1880 to 1998" 
keywords: Idaho, Latah County, Potlatch, Forests, Labor, Agriculture
menu: browse items map subjects #options - [browse,items,map,subjects,timeline,about]
csvtitle: phs
email: dbecker@uidaho.edu

# Collection Details
items: 1450
MediaType: documents, images
Location: Potlatch, Idaho
Lat: 46.922281
Long: -116.907683
TimeStart: 1880
TimeEnd: 1998
Image: http://digital.lib.uidaho.edu/utils/ajaxhelper/?CISOROOT=phs&CISOPTR=26&action=2&DMSCALE=30&DMWIDTH=812&DMHEIGHT=748&DMX=0&DMY=0&DMTEXT=&DMROTATE=0
ImageLink: http://digital.lib.uidaho.edu/cdm/ref/collection/phs/id/26
ImageTitle: Winter Logging
width: 621px
height: 448px

# repository variables (leave blank if self-contained)
repo-type: contentdm # options[contentdm,dspace,samvera,islandora,omeka]
repo-url: https://digital.lib.uidaho.edu 
repo-collection-id: phs
repo-link: on #options[on] - if on, will link to base repository item url outside of directory; if blank, will link to item url within directory, which will require the page-gen settings to be turned on below-- NOTE: these item pages will not work via Github Pages
# repository-name: jekyll-collection

# collection display variables 
# see _data/metadata-fields.csv

# page gen settings https://github.com/avillafiorita/jekyll-datapage_gen
# page_gen:
#  - data: 'barstock' #should be the same as your csvtitle above
#    template: 'items' 
#    name: 'object-id' #name of the unique identifier in your metadata sheet
 #   dir: 'items' #which directory you'd like your pages generated to
  #  extension: 'html'
