# Jekyll Digital Collection Generator

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build

# Site settings
title: White Pine Collection
tagline: White Pine - King of Many Waters Book Photographs
description: "White Pine - King of Many Waters Book Photographs" 
keywords: Idaho, Latah County, Potlatch, Forests, Labor, Agriculture
csvtitle: barstock
email: dbecker@uidaho.edu

# url variables
url: https://dcnb.github.io
baseurl: /jekyll-collection-contentdm

# repository variables (leave blank if self-contained)
repo-type: contentdm # options[contentdm,dspace,samvera,islandora,omeka]
repo-url: https://digital.lib.uidaho.edu 
repo-collection-id: bar-stock
repo-link: on #options[on] - if on, will link to base repository item url outside of directory; if blank, will link to item url within directory
# repository-name: jekyll-collection

# collection display variables 
# see _data/metadata-fields.csv

# page gen settings https://github.com/avillafiorita/jekyll-datapage_gen
# page_gen:
#  - data: 'barstock' #should be the same as your csvtitle above
#    template: 'items' 
#    name: 'object-id' #name of the unique identifier in your metadata sheet
 #   dir: 'items' #which directory you'd like your pages generated to
  #  extension: 'html'
