# Jekyll Digital Collection Generator

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build

# Site/Collection settings
title: Potlatch Historical Society Collection
tagline: Potlatch Historical Society Collection Depicting life in and around Potlatch, Idaho from 1880 to 1998
subjects: Idaho, Latah County, Potlatch, Forests, Labor, Agriculture #separate by comma(',')
description: "Potlatch Historical Society Collection Depicting life in and around Potlatch, Idaho from 1880 to 1998. The collection was built from items held by the Potlatch Historical Society in 2016-2017. Items were also added via digitization days held in Potlatch in 2017 and 2018. " 
mediatypes: documents, images #options[documents,images,video,sound,data] separate by comma(',')
locations: Potlatch, Idaho; Harvard, Idaho #separate by semi-colon(';')
latitude: 46.922281 #to determine center of map
longitude: -116.907683 #to determine center of map

# Site Population settings
csvtitle: phs 
pagetypes: subjects, map, items, timeline, about #options for pagetypes- [items,map,timeline,about] -- home, browse, and subjects are auotmatic
homepagetype: infographic # options for homepage type [basic,infographic]

# repository variables (leave blank if self-contained)
repo-url: https://digital.lib.uidaho.edu 
repo-collection-id: phs
repo-link: #options[on] - if on, will link to base repository item url outside of directory; if blank, will link to item url within directory, which will require the page-gen settings to be turned on below-- NOTE: these item pages will not work via Github Pages


email: dbecker@uidaho.edu
# Item Page Details

# collection  display variables 
# see _data/metadata-fields.csv

# page gen settings https://github.com/avillafiorita/jekyll-datapage_gen
page_gen:
  - data: 'phs' #should be the same as your csvtitle above
    template: 'items' 
    name: 'object-id' #name of the unique identifier in your metadata sheet
    dir: 'items' #which directory you'd like your pages generated to
    extension: 'html'
