# Jekyll Digital Collection Generator

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build

# Site/Collection settings
title: Donald R. Theophilus Boxing Photograph Collection
tagline: Photographs of University of Idaho Boxers and Boxing Teams, 1934 - 1953
subjects: UI; Idaho; Sports #separate semi-colon(';')
description: "A digital collection comprised of 52 photographs of boxers and boxing teams from the University of Idaho" 
mediatypes: images #options[documents,images,video,sound,data] separate semi-colon(';')
locations: University of Idaho; Sacramento, California; #separate by semi-colon(';')
latitude: 46.727485 #to determine center of map
longitude: -117.014185 #to determine center of map

# repository variables (leave blank if self-contained)
repo-url: https://digital.lib.uidaho.edu 
repo-collection-id: boxing
repo-link: on #options[on] - if on, will link to base repository item url outside of directory; if blank, will link to item url within directory, which will require the page-gen settings to be turned on below-- NOTE: these item pages will not work via Github Pages

# Site Population settings
csvtitle: boxing
pagetypes: data,map,timeline,about #options for pagetypes- [data,map,timeline,about] -- home, browse, and subjects are auotmatic
subjectsplit: subjects # options[subjects - whole subjects, including two word entries separted by semi-colon; words - breaks all subjects into individual words]
mapzoomlevel: 10 # options - 
datatable: title,creator,description,date,subjects,source # options any field on csv [title,creator,date,description,location,subjects,latitude,longitude,format,type,object-id]
image-percentage-small: 30
image-percentage-medium: 50
image-percentage-large: 80

# bootstrap themes and options 
navbar: dark # [dark (default),light, primary]
bstheme: Materia # leave blank or comment out for plain bootstrap
# For a bootswatch theme (https://bootswatch.com/) choose from any of the bootswatch themes listed below
# [Cerulean,Cosmo,Cyborg,Darkly,Flatly,Journal,Litera,Lumen,Lux,Materia,Minty,Pulse,Sandstone,Simplex,Sketchy,Slate,Solar,Spacelab,Superhero,United,Yeti]
# Note: to enable these, you'll need to rebuild/reserve the website or wait for GH-pages to do so. 

# url variables
# url: https://www.lib.uidaho.edu/digital/
# baseurl: /boxing
email: dbecker@uidaho.edu

# url variables
url: https://dcnb.github.io
baseurl: /jekyll-collection-contentdm

email: dbecker@uidaho.edu
# Item Page Details

# collection  display variables 
# see _data/metadata-fields.csv

# page gen settings https://github.com/avillafiorita/jekyll-datapage_gen
page_gen:
  - data: 'boxing' #should be the same as your csvtitle above
    template: 'items' 
    name: 'object-id' #name of the unique identifier in your metadata sheet
    dir: 'items' #which directory you'd like your pages generated to
    extension: 'html'
    
