# Jekyll Digital Collection Generator

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build

# Site/Collection settings
title: Psychiana Digital Collection
tagline: Materials from the Frank B. Robinson Papers documenting Psychiana, a religion popular in the 1930s and 40s
subjects: Idaho; Northwest; Latah; Religion #separate semi-colon(';')
description: "Materials from the Frank B. Robinson Papers documenting Psychiana, a religion popular in the 1930s and 40s" 
mediatypes: images; documents; audio; correspondence #options[documents,images,video,sound,data] separate semi-colon(';')
locations: Moscow, ID #separate by semi-colon(';')
latitude: 46.733711 #to determine center of map
longitude: -117.001252 #to determine center of map

# repository variables (leave blank if self-contained)
repo-url: https://digital.lib.uidaho.edu 
repo-collection-id: psychiana
repo-link: on #options[on] - if on, will link to base repository item url outside of directory; if blank, will link to item url within directory, which will require the page-gen settings to be turned on below-- NOTE: these item pages will not work via Github Pages

# Site Population settings
csvtitle: psychiana
pagetypes: data,map,timeline,about #options for pagetypes- [data,map,timeline,about] -- home, browse, and subjects are auotmatic
subjectsplit: subjects # options[subjects - whole subjects, including two word entries separted by semi-colon; words - breaks all subjects into individual words]
mapzoomlevel: 10 # options - 
datatable: title,creator,description,date,subjects,source # options any field on csv [title,creator,date,description,location,subjects,latitude,longitude,format,type,object-id]
image-percentage-small: 30
image-percentage-medium: 50
image-percentage-large: 80

# url variables
# url: https://www.lib.uidaho.edu/digital/
# baseurl: /psychiana
email: dbecker@uidaho.edu

# url variables
url: https://dcnb.github.io
baseurl: /jekyll-collection-contentdm

email: dbecker@uidaho.edu
# Item Page Details

# collection  display variables 
# see _data/metadata-fields.csv

# page gen settings https://github.com/avillafiorita/jekyll-datapage_gen
page_gen:
  - data: 'psychiana' #should be the same as your csvtitle above
    template: 'items' 
    name: 'object-id' #name of the unique identifier in your metadata sheet
    dir: 'items' #which directory you'd like your pages generated to
    extension: 'html'