# Jekyll Digital Collection Generator

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build

# Site settings
title: Title of Collection Site
tagline: A short description that appears in header
description: "A more complete description that will appear in meta tags and other locations where appropriate" 
keywords: university of idaho, digital collections, digital humanities
email: ewilliamson@uidaho.edu

# url variables
url: https://uidaholib.github.io
baseurl: /jekyll-collection

# repository variables (leave blank if self-contained)
repo-type: contentdm # options[contentdm,dspace,samvera,islandora,omeka]
repo-url: https://digital.lib.uidaho.edu 
repo-collection-id: guidedread
repo-link: off #options[on,off] - if on, will link to base repository item url outside of directory; if off or blank, will link to item url within directory
# repository-name: jekyll-collection

# collection display variables 
# see _data/metadata-fields.csv

# page gen settings https://github.com/avillafiorita/jekyll-datapage_gen
page_gen:
  - data: 'metadata'
    template: 'items'
    name: 'object-id'
    dir: 'items'
    extension: 'html'
